### PR TITLE
Handle incorrect sequence characters

### LINKED ISSUE #15: Improve handling of bad input
Increase the unit test coverage of bad input and throw ProFormaParseException (name pending) when needed

### PR DESCRIPTION
**Pull request by rfellers**
Very simple AA error handling, Closes #15. Also tacked on some .sln level project dependencies so things build properly (e.g. building the test project will automatically build the library project as needed)

### CODE REVIEW

File: LibraryProject1/ProForma/ProFormaParser.cs [hunk 1]
```diff
@@ -41,7 +41,15 @@ public ProFormaTerm ParseString(string proFormaString)
                 else if (inTag)
                     tag.Append(current);
                 else
+                {
+                    // Validate amino acid character
+                    if (!char.IsUpper(current))
+                        throw new ProFormaParseException($"{current} is not an upper case letter.");
+                    else if (current == 'X')
```
Comment (acesnik) [inline LibraryProject1/ProForma/ProFormaParser.cs]: Looks like char.IsUpper() returns false for '*' and '-', so that's good.

File: TestProject1/ProFormaParserTests.cs [hunk 2]
```diff
@@ -97,6 +97,17 @@ public void MixedDescriptor()
             Assert.AreEqual("+14.02", tag.Descriptors.Last().Value);
         }
 
+        [Test]
+        [TestCase("PROTEOFXRM")]
+        [TestCase("PROTEOF@RM")]
+        [TestCase("proteoform")]
```
Comment (acesnik) [inline TestProject1/ProFormaParserTests.cs]: We could add one with a '*' for a stop codon to make sure we don't break that in the future somehow.
